services:
  db:
    image: louta/sqlpinoteca:v1
    container_name: contenedorPinoteca
    ports:
      - "3306:3306"

  php:
    image: louta/phppinoteca:v1
    container_name: contenedorPinoteca
    ports:
      - "8080:80"
    depends_on:
      - db
